# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from GRPC.PersonalData import IPersonalDataServiceGrpc_pb2 as IPersonalDataServiceGrpc__pb2
from GRPC.UsefulImport import empty_pb2 as empty__pb2

class PersonalDataServiceGrpcStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Confirm = channel.unary_unary(
                '/Service.PersonalData.Grpc.PersonalDataServiceGrpc/Confirm',
                request_serializer=IPersonalDataServiceGrpc__pb2.ConfirmGrpcModel.SerializeToString,
                response_deserializer=empty__pb2.Empty.FromString,
                )
        self.ConfirmPhone = channel.unary_unary(
                '/Service.PersonalData.Grpc.PersonalDataServiceGrpc/ConfirmPhone',
                request_serializer=IPersonalDataServiceGrpc__pb2.ConfirmGrpcModel.SerializeToString,
                response_deserializer=empty__pb2.Empty.FromString,
                )
        self.Get = channel.unary_unary(
                '/Service.PersonalData.Grpc.PersonalDataServiceGrpc/Get',
                request_serializer=IPersonalDataServiceGrpc__pb2.GetRequest.SerializeToString,
                response_deserializer=IPersonalDataServiceGrpc__pb2.PersonalDataBatchResponseContract.FromString,
                )
        self.GetByEmail = channel.unary_unary(
                '/Service.PersonalData.Grpc.PersonalDataServiceGrpc/GetByEmail',
                request_serializer=IPersonalDataServiceGrpc__pb2.GetByEmailRequest.SerializeToString,
                response_deserializer=IPersonalDataServiceGrpc__pb2.PersonalDataGrpcResponseContract.FromString,
                )
        self.GetById = channel.unary_unary(
                '/Service.PersonalData.Grpc.PersonalDataServiceGrpc/GetById',
                request_serializer=IPersonalDataServiceGrpc__pb2.GetByIdRequest.SerializeToString,
                response_deserializer=IPersonalDataServiceGrpc__pb2.PersonalDataGrpcResponseContract.FromString,
                )
        self.GetByIds = channel.unary_unary(
                '/Service.PersonalData.Grpc.PersonalDataServiceGrpc/GetByIds',
                request_serializer=IPersonalDataServiceGrpc__pb2.GetByIdsRequest.SerializeToString,
                response_deserializer=IPersonalDataServiceGrpc__pb2.PersonalDataBatchResponseContract.FromString,
                )
        self.GetByPhone = channel.unary_unary(
                '/Service.PersonalData.Grpc.PersonalDataServiceGrpc/GetByPhone',
                request_serializer=IPersonalDataServiceGrpc__pb2.GetByPhoneRequest.SerializeToString,
                response_deserializer=IPersonalDataServiceGrpc__pb2.PersonalDataGrpcResponseContract.FromString,
                )
        self.GetPersonalDataByStatus = channel.unary_unary(
                '/Service.PersonalData.Grpc.PersonalDataServiceGrpc/GetPersonalDataByStatus',
                request_serializer=IPersonalDataServiceGrpc__pb2.GetPersonalDataByStatusRequest.SerializeToString,
                response_deserializer=IPersonalDataServiceGrpc__pb2.GetPersonalDataByStatusResponse.FromString,
                )
        self.GetTotal = channel.unary_unary(
                '/Service.PersonalData.Grpc.PersonalDataServiceGrpc/GetTotal',
                request_serializer=empty__pb2.Empty.SerializeToString,
                response_deserializer=IPersonalDataServiceGrpc__pb2.GetTotalResponse.FromString,
                )
        self.Register = channel.unary_unary(
                '/Service.PersonalData.Grpc.PersonalDataServiceGrpc/Register',
                request_serializer=IPersonalDataServiceGrpc__pb2.RegisterPersonalDataGrpcModel.SerializeToString,
                response_deserializer=IPersonalDataServiceGrpc__pb2.ResultGrpcResponse.FromString,
                )
        self.Search = channel.unary_unary(
                '/Service.PersonalData.Grpc.PersonalDataServiceGrpc/Search',
                request_serializer=IPersonalDataServiceGrpc__pb2.SearchRequest.SerializeToString,
                response_deserializer=IPersonalDataServiceGrpc__pb2.PersonalDataBatchResponseContract.FromString,
                )
        self.Update = channel.unary_unary(
                '/Service.PersonalData.Grpc.PersonalDataServiceGrpc/Update',
                request_serializer=IPersonalDataServiceGrpc__pb2.UpdatePersonalDataGrpcContract.SerializeToString,
                response_deserializer=IPersonalDataServiceGrpc__pb2.ResultGrpcResponse.FromString,
                )
        self.UpdateKyc = channel.unary_unary(
                '/Service.PersonalData.Grpc.PersonalDataServiceGrpc/UpdateKyc',
                request_serializer=IPersonalDataServiceGrpc__pb2.UpdateKycGrpcContract.SerializeToString,
                response_deserializer=empty__pb2.Empty.FromString,
                )


class PersonalDataServiceGrpcServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Confirm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmPhone(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetByEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetByIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetByPhone(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPersonalDataByStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTotal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateKyc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PersonalDataServiceGrpcServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Confirm': grpc.unary_unary_rpc_method_handler(
                    servicer.Confirm,
                    request_deserializer=IPersonalDataServiceGrpc__pb2.ConfirmGrpcModel.FromString,
                    response_serializer=empty__pb2.Empty.SerializeToString,
            ),
            'ConfirmPhone': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmPhone,
                    request_deserializer=IPersonalDataServiceGrpc__pb2.ConfirmGrpcModel.FromString,
                    response_serializer=empty__pb2.Empty.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=IPersonalDataServiceGrpc__pb2.GetRequest.FromString,
                    response_serializer=IPersonalDataServiceGrpc__pb2.PersonalDataBatchResponseContract.SerializeToString,
            ),
            'GetByEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetByEmail,
                    request_deserializer=IPersonalDataServiceGrpc__pb2.GetByEmailRequest.FromString,
                    response_serializer=IPersonalDataServiceGrpc__pb2.PersonalDataGrpcResponseContract.SerializeToString,
            ),
            'GetById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetById,
                    request_deserializer=IPersonalDataServiceGrpc__pb2.GetByIdRequest.FromString,
                    response_serializer=IPersonalDataServiceGrpc__pb2.PersonalDataGrpcResponseContract.SerializeToString,
            ),
            'GetByIds': grpc.unary_unary_rpc_method_handler(
                    servicer.GetByIds,
                    request_deserializer=IPersonalDataServiceGrpc__pb2.GetByIdsRequest.FromString,
                    response_serializer=IPersonalDataServiceGrpc__pb2.PersonalDataBatchResponseContract.SerializeToString,
            ),
            'GetByPhone': grpc.unary_unary_rpc_method_handler(
                    servicer.GetByPhone,
                    request_deserializer=IPersonalDataServiceGrpc__pb2.GetByPhoneRequest.FromString,
                    response_serializer=IPersonalDataServiceGrpc__pb2.PersonalDataGrpcResponseContract.SerializeToString,
            ),
            'GetPersonalDataByStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPersonalDataByStatus,
                    request_deserializer=IPersonalDataServiceGrpc__pb2.GetPersonalDataByStatusRequest.FromString,
                    response_serializer=IPersonalDataServiceGrpc__pb2.GetPersonalDataByStatusResponse.SerializeToString,
            ),
            'GetTotal': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTotal,
                    request_deserializer=empty__pb2.Empty.FromString,
                    response_serializer=IPersonalDataServiceGrpc__pb2.GetTotalResponse.SerializeToString,
            ),
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=IPersonalDataServiceGrpc__pb2.RegisterPersonalDataGrpcModel.FromString,
                    response_serializer=IPersonalDataServiceGrpc__pb2.ResultGrpcResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=IPersonalDataServiceGrpc__pb2.SearchRequest.FromString,
                    response_serializer=IPersonalDataServiceGrpc__pb2.PersonalDataBatchResponseContract.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=IPersonalDataServiceGrpc__pb2.UpdatePersonalDataGrpcContract.FromString,
                    response_serializer=IPersonalDataServiceGrpc__pb2.ResultGrpcResponse.SerializeToString,
            ),
            'UpdateKyc': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateKyc,
                    request_deserializer=IPersonalDataServiceGrpc__pb2.UpdateKycGrpcContract.FromString,
                    response_serializer=empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Service.PersonalData.Grpc.PersonalDataServiceGrpc', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PersonalDataServiceGrpc(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Confirm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service.PersonalData.Grpc.PersonalDataServiceGrpc/Confirm',
            IPersonalDataServiceGrpc__pb2.ConfirmGrpcModel.SerializeToString,
            empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConfirmPhone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service.PersonalData.Grpc.PersonalDataServiceGrpc/ConfirmPhone',
            IPersonalDataServiceGrpc__pb2.ConfirmGrpcModel.SerializeToString,
            empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service.PersonalData.Grpc.PersonalDataServiceGrpc/Get',
            IPersonalDataServiceGrpc__pb2.GetRequest.SerializeToString,
            IPersonalDataServiceGrpc__pb2.PersonalDataBatchResponseContract.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetByEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service.PersonalData.Grpc.PersonalDataServiceGrpc/GetByEmail',
            IPersonalDataServiceGrpc__pb2.GetByEmailRequest.SerializeToString,
            IPersonalDataServiceGrpc__pb2.PersonalDataGrpcResponseContract.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service.PersonalData.Grpc.PersonalDataServiceGrpc/GetById',
            IPersonalDataServiceGrpc__pb2.GetByIdRequest.SerializeToString,
            IPersonalDataServiceGrpc__pb2.PersonalDataGrpcResponseContract.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetByIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service.PersonalData.Grpc.PersonalDataServiceGrpc/GetByIds',
            IPersonalDataServiceGrpc__pb2.GetByIdsRequest.SerializeToString,
            IPersonalDataServiceGrpc__pb2.PersonalDataBatchResponseContract.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetByPhone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service.PersonalData.Grpc.PersonalDataServiceGrpc/GetByPhone',
            IPersonalDataServiceGrpc__pb2.GetByPhoneRequest.SerializeToString,
            IPersonalDataServiceGrpc__pb2.PersonalDataGrpcResponseContract.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPersonalDataByStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service.PersonalData.Grpc.PersonalDataServiceGrpc/GetPersonalDataByStatus',
            IPersonalDataServiceGrpc__pb2.GetPersonalDataByStatusRequest.SerializeToString,
            IPersonalDataServiceGrpc__pb2.GetPersonalDataByStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTotal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service.PersonalData.Grpc.PersonalDataServiceGrpc/GetTotal',
            empty__pb2.Empty.SerializeToString,
            IPersonalDataServiceGrpc__pb2.GetTotalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service.PersonalData.Grpc.PersonalDataServiceGrpc/Register',
            IPersonalDataServiceGrpc__pb2.RegisterPersonalDataGrpcModel.SerializeToString,
            IPersonalDataServiceGrpc__pb2.ResultGrpcResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service.PersonalData.Grpc.PersonalDataServiceGrpc/Search',
            IPersonalDataServiceGrpc__pb2.SearchRequest.SerializeToString,
            IPersonalDataServiceGrpc__pb2.PersonalDataBatchResponseContract.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service.PersonalData.Grpc.PersonalDataServiceGrpc/Update',
            IPersonalDataServiceGrpc__pb2.UpdatePersonalDataGrpcContract.SerializeToString,
            IPersonalDataServiceGrpc__pb2.ResultGrpcResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateKyc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service.PersonalData.Grpc.PersonalDataServiceGrpc/UpdateKyc',
            IPersonalDataServiceGrpc__pb2.UpdateKycGrpcContract.SerializeToString,
            empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
