# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Helper.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

# from new_change_balance import bcl_pb2 as bcl__pb2
from GRPC.UsefulImport import bcl_pb2 as bcl__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Helper.proto',
  package='MyJetWallet.Sdk.GrpcSchema',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cHelper.proto\x12\x1aMyJetWallet.Sdk.GrpcSchema\x1a\tbcl.proto\"-\n\rData_DateTime\x12\x1c\n\x05Value\x18\x01 \x01(\x0b\x32\r.bcl.DateTime\"+\n\x0c\x44\x61ta_Decimal\x12\x1b\n\x05Value\x18\x01 \x01(\x0b\x32\x0c.bcl.Decimal\"\x1c\n\x0b\x44\x61ta_String\x12\r\n\x05Value\x18\x01 \x01(\t2\xaf\x03\n\x11GrpcHelperService\x12\x66\n\x10\x44\x61teTimeToString\x12).MyJetWallet.Sdk.GrpcSchema.Data_DateTime\x1a\'.MyJetWallet.Sdk.GrpcSchema.Data_String\x12\x64\n\x0f\x44\x65\x63imalToString\x12(.MyJetWallet.Sdk.GrpcSchema.Data_Decimal\x1a\'.MyJetWallet.Sdk.GrpcSchema.Data_String\x12\x66\n\x10StringToDateTime\x12\'.MyJetWallet.Sdk.GrpcSchema.Data_String\x1a).MyJetWallet.Sdk.GrpcSchema.Data_DateTime\x12\x64\n\x0fStringToDecimal\x12\'.MyJetWallet.Sdk.GrpcSchema.Data_String\x1a(.MyJetWallet.Sdk.GrpcSchema.Data_Decimalb\x06proto3'
  ,
  dependencies=[bcl__pb2.DESCRIPTOR,])




_DATA_DATETIME = _descriptor.Descriptor(
  name='Data_DateTime',
  full_name='MyJetWallet.Sdk.GrpcSchema.Data_DateTime',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Value', full_name='MyJetWallet.Sdk.GrpcSchema.Data_DateTime.Value', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=100,
)


_DATA_DECIMAL = _descriptor.Descriptor(
  name='Data_Decimal',
  full_name='MyJetWallet.Sdk.GrpcSchema.Data_Decimal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Value', full_name='MyJetWallet.Sdk.GrpcSchema.Data_Decimal.Value', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=145,
)


_DATA_STRING = _descriptor.Descriptor(
  name='Data_String',
  full_name='MyJetWallet.Sdk.GrpcSchema.Data_String',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Value', full_name='MyJetWallet.Sdk.GrpcSchema.Data_String.Value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=175,
)

_DATA_DATETIME.fields_by_name['Value'].message_type = bcl__pb2._DATETIME
_DATA_DECIMAL.fields_by_name['Value'].message_type = bcl__pb2._DECIMAL
DESCRIPTOR.message_types_by_name['Data_DateTime'] = _DATA_DATETIME
DESCRIPTOR.message_types_by_name['Data_Decimal'] = _DATA_DECIMAL
DESCRIPTOR.message_types_by_name['Data_String'] = _DATA_STRING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Data_DateTime = _reflection.GeneratedProtocolMessageType('Data_DateTime', (_message.Message,), {
  'DESCRIPTOR' : _DATA_DATETIME,
  '__module__' : 'Helper_pb2'
  # @@protoc_insertion_point(class_scope:MyJetWallet.Sdk.GrpcSchema.Data_DateTime)
  })
_sym_db.RegisterMessage(Data_DateTime)

Data_Decimal = _reflection.GeneratedProtocolMessageType('Data_Decimal', (_message.Message,), {
  'DESCRIPTOR' : _DATA_DECIMAL,
  '__module__' : 'Helper_pb2'
  # @@protoc_insertion_point(class_scope:MyJetWallet.Sdk.GrpcSchema.Data_Decimal)
  })
_sym_db.RegisterMessage(Data_Decimal)

Data_String = _reflection.GeneratedProtocolMessageType('Data_String', (_message.Message,), {
  'DESCRIPTOR' : _DATA_STRING,
  '__module__' : 'Helper_pb2'
  # @@protoc_insertion_point(class_scope:MyJetWallet.Sdk.GrpcSchema.Data_String)
  })
_sym_db.RegisterMessage(Data_String)



_GRPCHELPERSERVICE = _descriptor.ServiceDescriptor(
  name='GrpcHelperService',
  full_name='MyJetWallet.Sdk.GrpcSchema.GrpcHelperService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=178,
  serialized_end=609,
  methods=[
  _descriptor.MethodDescriptor(
    name='DateTimeToString',
    full_name='MyJetWallet.Sdk.GrpcSchema.GrpcHelperService.DateTimeToString',
    index=0,
    containing_service=None,
    input_type=_DATA_DATETIME,
    output_type=_DATA_STRING,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DecimalToString',
    full_name='MyJetWallet.Sdk.GrpcSchema.GrpcHelperService.DecimalToString',
    index=1,
    containing_service=None,
    input_type=_DATA_DECIMAL,
    output_type=_DATA_STRING,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StringToDateTime',
    full_name='MyJetWallet.Sdk.GrpcSchema.GrpcHelperService.StringToDateTime',
    index=2,
    containing_service=None,
    input_type=_DATA_STRING,
    output_type=_DATA_DATETIME,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StringToDecimal',
    full_name='MyJetWallet.Sdk.GrpcSchema.GrpcHelperService.StringToDecimal',
    index=3,
    containing_service=None,
    input_type=_DATA_STRING,
    output_type=_DATA_DECIMAL,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GRPCHELPERSERVICE)

DESCRIPTOR.services_by_name['GrpcHelperService'] = _GRPCHELPERSERVICE

# @@protoc_insertion_point(module_scope)
