# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

# import Helper_pb2 as Helper__pb2
# from new_change_balance import Helper_pb2 as Helper__pb2
from GRPC.Helper import Helper_pb2 as Helper__pb2

class GrpcHelperServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DateTimeToString = channel.unary_unary(
                '/MyJetWallet.Sdk.GrpcSchema.GrpcHelperService/DateTimeToString',
                request_serializer=Helper__pb2.Data_DateTime.SerializeToString,
                response_deserializer=Helper__pb2.Data_String.FromString,
                )
        self.DecimalToString = channel.unary_unary(
                '/MyJetWallet.Sdk.GrpcSchema.GrpcHelperService/DecimalToString',
                request_serializer=Helper__pb2.Data_Decimal.SerializeToString,
                response_deserializer=Helper__pb2.Data_String.FromString,
                )
        self.StringToDateTime = channel.unary_unary(
                '/MyJetWallet.Sdk.GrpcSchema.GrpcHelperService/StringToDateTime',
                request_serializer=Helper__pb2.Data_String.SerializeToString,
                response_deserializer=Helper__pb2.Data_DateTime.FromString,
                )
        self.StringToDecimal = channel.unary_unary(
                '/MyJetWallet.Sdk.GrpcSchema.GrpcHelperService/StringToDecimal',
                request_serializer=Helper__pb2.Data_String.SerializeToString,
                response_deserializer=Helper__pb2.Data_Decimal.FromString,
                )


class GrpcHelperServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DateTimeToString(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecimalToString(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StringToDateTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StringToDecimal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GrpcHelperServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DateTimeToString': grpc.unary_unary_rpc_method_handler(
                    servicer.DateTimeToString,
                    request_deserializer=Helper__pb2.Data_DateTime.FromString,
                    response_serializer=Helper__pb2.Data_String.SerializeToString,
            ),
            'DecimalToString': grpc.unary_unary_rpc_method_handler(
                    servicer.DecimalToString,
                    request_deserializer=Helper__pb2.Data_Decimal.FromString,
                    response_serializer=Helper__pb2.Data_String.SerializeToString,
            ),
            'StringToDateTime': grpc.unary_unary_rpc_method_handler(
                    servicer.StringToDateTime,
                    request_deserializer=Helper__pb2.Data_String.FromString,
                    response_serializer=Helper__pb2.Data_DateTime.SerializeToString,
            ),
            'StringToDecimal': grpc.unary_unary_rpc_method_handler(
                    servicer.StringToDecimal,
                    request_deserializer=Helper__pb2.Data_String.FromString,
                    response_serializer=Helper__pb2.Data_Decimal.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MyJetWallet.Sdk.GrpcSchema.GrpcHelperService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GrpcHelperService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DateTimeToString(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MyJetWallet.Sdk.GrpcSchema.GrpcHelperService/DateTimeToString',
            Helper__pb2.Data_DateTime.SerializeToString,
            Helper__pb2.Data_String.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DecimalToString(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MyJetWallet.Sdk.GrpcSchema.GrpcHelperService/DecimalToString',
            Helper__pb2.Data_Decimal.SerializeToString,
            Helper__pb2.Data_String.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StringToDateTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MyJetWallet.Sdk.GrpcSchema.GrpcHelperService/StringToDateTime',
            Helper__pb2.Data_String.SerializeToString,
            Helper__pb2.Data_DateTime.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StringToDecimal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MyJetWallet.Sdk.GrpcSchema.GrpcHelperService/StringToDecimal',
            Helper__pb2.Data_String.SerializeToString,
            Helper__pb2.Data_Decimal.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
