# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from GRPC.AssetsInfo import IAssetsDictionaryService_pb2 as IAssetsDictionaryService__pb2


class AssetsDictionaryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAsset = channel.unary_unary(
                '/Service.AssetsDictionary.Grpc.AssetsDictionaryService/CreateAsset',
                request_serializer=IAssetsDictionaryService__pb2.Asset.SerializeToString,
                response_deserializer=IAssetsDictionaryService__pb2.AssetDictionaryResponse_Asset.FromString,
                )
        self.DeleteAsset = channel.unary_unary(
                '/Service.AssetsDictionary.Grpc.AssetsDictionaryService/DeleteAsset',
                request_serializer=IAssetsDictionaryService__pb2.Asset.SerializeToString,
                response_deserializer=IAssetsDictionaryService__pb2.AssetDictionaryResponse_Asset.FromString,
                )
        self.GetAssetById = channel.unary_unary(
                '/Service.AssetsDictionary.Grpc.AssetsDictionaryService/GetAssetById',
                request_serializer=IAssetsDictionaryService__pb2.AssetIdentity.SerializeToString,
                response_deserializer=IAssetsDictionaryService__pb2.NullableValue_Asset.FromString,
                )
        self.GetAssetsByBroker = channel.unary_unary(
                '/Service.AssetsDictionary.Grpc.AssetsDictionaryService/GetAssetsByBroker',
                request_serializer=IAssetsDictionaryService__pb2.JetBrokerIdentity.SerializeToString,
                response_deserializer=IAssetsDictionaryService__pb2.AssetsListResponse.FromString,
                )
        self.UpdateAsset = channel.unary_unary(
                '/Service.AssetsDictionary.Grpc.AssetsDictionaryService/UpdateAsset',
                request_serializer=IAssetsDictionaryService__pb2.Asset.SerializeToString,
                response_deserializer=IAssetsDictionaryService__pb2.AssetDictionaryResponse_Asset.FromString,
                )


class AssetsDictionaryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateAsset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAsset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAssetById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAssetsByBroker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAsset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AssetsDictionaryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAsset': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAsset,
                    request_deserializer=IAssetsDictionaryService__pb2.Asset.FromString,
                    response_serializer=IAssetsDictionaryService__pb2.AssetDictionaryResponse_Asset.SerializeToString,
            ),
            'DeleteAsset': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAsset,
                    request_deserializer=IAssetsDictionaryService__pb2.Asset.FromString,
                    response_serializer=IAssetsDictionaryService__pb2.AssetDictionaryResponse_Asset.SerializeToString,
            ),
            'GetAssetById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAssetById,
                    request_deserializer=IAssetsDictionaryService__pb2.AssetIdentity.FromString,
                    response_serializer=IAssetsDictionaryService__pb2.NullableValue_Asset.SerializeToString,
            ),
            'GetAssetsByBroker': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAssetsByBroker,
                    request_deserializer=IAssetsDictionaryService__pb2.JetBrokerIdentity.FromString,
                    response_serializer=IAssetsDictionaryService__pb2.AssetsListResponse.SerializeToString,
            ),
            'UpdateAsset': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAsset,
                    request_deserializer=IAssetsDictionaryService__pb2.Asset.FromString,
                    response_serializer=IAssetsDictionaryService__pb2.AssetDictionaryResponse_Asset.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Service.AssetsDictionary.Grpc.AssetsDictionaryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AssetsDictionaryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateAsset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service.AssetsDictionary.Grpc.AssetsDictionaryService/CreateAsset',
            IAssetsDictionaryService__pb2.Asset.SerializeToString,
            IAssetsDictionaryService__pb2.AssetDictionaryResponse_Asset.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteAsset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service.AssetsDictionary.Grpc.AssetsDictionaryService/DeleteAsset',
            IAssetsDictionaryService__pb2.Asset.SerializeToString,
            IAssetsDictionaryService__pb2.AssetDictionaryResponse_Asset.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAssetById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service.AssetsDictionary.Grpc.AssetsDictionaryService/GetAssetById',
            IAssetsDictionaryService__pb2.AssetIdentity.SerializeToString,
            IAssetsDictionaryService__pb2.NullableValue_Asset.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAssetsByBroker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service.AssetsDictionary.Grpc.AssetsDictionaryService/GetAssetsByBroker',
            IAssetsDictionaryService__pb2.JetBrokerIdentity.SerializeToString,
            IAssetsDictionaryService__pb2.AssetsListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateAsset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service.AssetsDictionary.Grpc.AssetsDictionaryService/UpdateAsset',
            IAssetsDictionaryService__pb2.Asset.SerializeToString,
            IAssetsDictionaryService__pb2.AssetDictionaryResponse_Asset.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
