# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from GRPC.ChangeBalance import ChangeBalance_pb2 as ChangeBalance__pb2


class SpotChangeBalanceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BlockchainDeposit = channel.unary_unary(
                '/Service.ChangeBalanceGateway.Grpc.SpotChangeBalanceService/BlockchainDeposit',
                request_serializer=ChangeBalance__pb2.BlockchainDepositGrpcRequest.SerializeToString,
                response_deserializer=ChangeBalance__pb2.ChangeBalanceGrpcResponse.FromString,
                )
        self.BlockchainFeeApply = channel.unary_unary(
                '/Service.ChangeBalanceGateway.Grpc.SpotChangeBalanceService/BlockchainFeeApply',
                request_serializer=ChangeBalance__pb2.BlockchainFeeApplyGrpcRequest.SerializeToString,
                response_deserializer=ChangeBalance__pb2.ChangeBalanceGrpcResponse.FromString,
                )
        self.BlockchainWithdrawal = channel.unary_unary(
                '/Service.ChangeBalanceGateway.Grpc.SpotChangeBalanceService/BlockchainWithdrawal',
                request_serializer=ChangeBalance__pb2.BlockchainWithdrawalGrpcRequest.SerializeToString,
                response_deserializer=ChangeBalance__pb2.ChangeBalanceGrpcResponse.FromString,
                )
        self.InternalTransfer = channel.unary_unary(
                '/Service.ChangeBalanceGateway.Grpc.SpotChangeBalanceService/InternalTransfer',
                request_serializer=ChangeBalance__pb2.InternalTransferGrpcRequest.SerializeToString,
                response_deserializer=ChangeBalance__pb2.ChangeBalanceGrpcResponse.FromString,
                )
        self.ManualChangeBalance = channel.unary_unary(
                '/Service.ChangeBalanceGateway.Grpc.SpotChangeBalanceService/ManualChangeBalance',
                request_serializer=ChangeBalance__pb2.ManualChangeBalanceGrpcRequest.SerializeToString,
                response_deserializer=ChangeBalance__pb2.ChangeBalanceGrpcResponse.FromString,
                )
        self.PayBonusReward = channel.unary_unary(
                '/Service.ChangeBalanceGateway.Grpc.SpotChangeBalanceService/PayBonusReward',
                request_serializer=ChangeBalance__pb2.FeeTransferRequest.SerializeToString,
                response_deserializer=ChangeBalance__pb2.ChangeBalanceGrpcResponse.FromString,
                )
        self.PayFeeSharesToReferrer = channel.unary_unary(
                '/Service.ChangeBalanceGateway.Grpc.SpotChangeBalanceService/PayFeeSharesToReferrer',
                request_serializer=ChangeBalance__pb2.FeeTransferRequest.SerializeToString,
                response_deserializer=ChangeBalance__pb2.ChangeBalanceGrpcResponse.FromString,
                )
        self.PayInterestRate = channel.unary_unary(
                '/Service.ChangeBalanceGateway.Grpc.SpotChangeBalanceService/PayInterestRate',
                request_serializer=ChangeBalance__pb2.PayInterestRateRequest.SerializeToString,
                response_deserializer=ChangeBalance__pb2.ChangeBalanceGrpcResponse.FromString,
                )
        self.PciDssDeposit = channel.unary_unary(
                '/Service.ChangeBalanceGateway.Grpc.SpotChangeBalanceService/PciDssDeposit',
                request_serializer=ChangeBalance__pb2.PciDssDepositGrpcRequest.SerializeToString,
                response_deserializer=ChangeBalance__pb2.ChangeBalanceGrpcResponse.FromString,
                )
        self.Swap = channel.unary_unary(
                '/Service.ChangeBalanceGateway.Grpc.SpotChangeBalanceService/Swap',
                request_serializer=ChangeBalance__pb2.SwapGrpcRequest.SerializeToString,
                response_deserializer=ChangeBalance__pb2.ChangeBalanceGrpcResponse.FromString,
                )
        self.TransferFeeShareToServiceWallet = channel.unary_unary(
                '/Service.ChangeBalanceGateway.Grpc.SpotChangeBalanceService/TransferFeeShareToServiceWallet',
                request_serializer=ChangeBalance__pb2.FeeTransferRequest.SerializeToString,
                response_deserializer=ChangeBalance__pb2.ChangeBalanceGrpcResponse.FromString,
                )


class SpotChangeBalanceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BlockchainDeposit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BlockchainFeeApply(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BlockchainWithdrawal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InternalTransfer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ManualChangeBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PayBonusReward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PayFeeSharesToReferrer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PayInterestRate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PciDssDeposit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Swap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransferFeeShareToServiceWallet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpotChangeBalanceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BlockchainDeposit': grpc.unary_unary_rpc_method_handler(
                    servicer.BlockchainDeposit,
                    request_deserializer=ChangeBalance__pb2.BlockchainDepositGrpcRequest.FromString,
                    response_serializer=ChangeBalance__pb2.ChangeBalanceGrpcResponse.SerializeToString,
            ),
            'BlockchainFeeApply': grpc.unary_unary_rpc_method_handler(
                    servicer.BlockchainFeeApply,
                    request_deserializer=ChangeBalance__pb2.BlockchainFeeApplyGrpcRequest.FromString,
                    response_serializer=ChangeBalance__pb2.ChangeBalanceGrpcResponse.SerializeToString,
            ),
            'BlockchainWithdrawal': grpc.unary_unary_rpc_method_handler(
                    servicer.BlockchainWithdrawal,
                    request_deserializer=ChangeBalance__pb2.BlockchainWithdrawalGrpcRequest.FromString,
                    response_serializer=ChangeBalance__pb2.ChangeBalanceGrpcResponse.SerializeToString,
            ),
            'InternalTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.InternalTransfer,
                    request_deserializer=ChangeBalance__pb2.InternalTransferGrpcRequest.FromString,
                    response_serializer=ChangeBalance__pb2.ChangeBalanceGrpcResponse.SerializeToString,
            ),
            'ManualChangeBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.ManualChangeBalance,
                    request_deserializer=ChangeBalance__pb2.ManualChangeBalanceGrpcRequest.FromString,
                    response_serializer=ChangeBalance__pb2.ChangeBalanceGrpcResponse.SerializeToString,
            ),
            'PayBonusReward': grpc.unary_unary_rpc_method_handler(
                    servicer.PayBonusReward,
                    request_deserializer=ChangeBalance__pb2.FeeTransferRequest.FromString,
                    response_serializer=ChangeBalance__pb2.ChangeBalanceGrpcResponse.SerializeToString,
            ),
            'PayFeeSharesToReferrer': grpc.unary_unary_rpc_method_handler(
                    servicer.PayFeeSharesToReferrer,
                    request_deserializer=ChangeBalance__pb2.FeeTransferRequest.FromString,
                    response_serializer=ChangeBalance__pb2.ChangeBalanceGrpcResponse.SerializeToString,
            ),
            'PayInterestRate': grpc.unary_unary_rpc_method_handler(
                    servicer.PayInterestRate,
                    request_deserializer=ChangeBalance__pb2.PayInterestRateRequest.FromString,
                    response_serializer=ChangeBalance__pb2.ChangeBalanceGrpcResponse.SerializeToString,
            ),
            'PciDssDeposit': grpc.unary_unary_rpc_method_handler(
                    servicer.PciDssDeposit,
                    request_deserializer=ChangeBalance__pb2.PciDssDepositGrpcRequest.FromString,
                    response_serializer=ChangeBalance__pb2.ChangeBalanceGrpcResponse.SerializeToString,
            ),
            'Swap': grpc.unary_unary_rpc_method_handler(
                    servicer.Swap,
                    request_deserializer=ChangeBalance__pb2.SwapGrpcRequest.FromString,
                    response_serializer=ChangeBalance__pb2.ChangeBalanceGrpcResponse.SerializeToString,
            ),
            'TransferFeeShareToServiceWallet': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferFeeShareToServiceWallet,
                    request_deserializer=ChangeBalance__pb2.FeeTransferRequest.FromString,
                    response_serializer=ChangeBalance__pb2.ChangeBalanceGrpcResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Service.ChangeBalanceGateway.Grpc.SpotChangeBalanceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SpotChangeBalanceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BlockchainDeposit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service.ChangeBalanceGateway.Grpc.SpotChangeBalanceService/BlockchainDeposit',
            ChangeBalance__pb2.BlockchainDepositGrpcRequest.SerializeToString,
            ChangeBalance__pb2.ChangeBalanceGrpcResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BlockchainFeeApply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service.ChangeBalanceGateway.Grpc.SpotChangeBalanceService/BlockchainFeeApply',
            ChangeBalance__pb2.BlockchainFeeApplyGrpcRequest.SerializeToString,
            ChangeBalance__pb2.ChangeBalanceGrpcResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BlockchainWithdrawal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service.ChangeBalanceGateway.Grpc.SpotChangeBalanceService/BlockchainWithdrawal',
            ChangeBalance__pb2.BlockchainWithdrawalGrpcRequest.SerializeToString,
            ChangeBalance__pb2.ChangeBalanceGrpcResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InternalTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service.ChangeBalanceGateway.Grpc.SpotChangeBalanceService/InternalTransfer',
            ChangeBalance__pb2.InternalTransferGrpcRequest.SerializeToString,
            ChangeBalance__pb2.ChangeBalanceGrpcResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ManualChangeBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service.ChangeBalanceGateway.Grpc.SpotChangeBalanceService/ManualChangeBalance',
            ChangeBalance__pb2.ManualChangeBalanceGrpcRequest.SerializeToString,
            ChangeBalance__pb2.ChangeBalanceGrpcResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PayBonusReward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service.ChangeBalanceGateway.Grpc.SpotChangeBalanceService/PayBonusReward',
            ChangeBalance__pb2.FeeTransferRequest.SerializeToString,
            ChangeBalance__pb2.ChangeBalanceGrpcResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PayFeeSharesToReferrer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service.ChangeBalanceGateway.Grpc.SpotChangeBalanceService/PayFeeSharesToReferrer',
            ChangeBalance__pb2.FeeTransferRequest.SerializeToString,
            ChangeBalance__pb2.ChangeBalanceGrpcResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PayInterestRate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service.ChangeBalanceGateway.Grpc.SpotChangeBalanceService/PayInterestRate',
            ChangeBalance__pb2.PayInterestRateRequest.SerializeToString,
            ChangeBalance__pb2.ChangeBalanceGrpcResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PciDssDeposit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service.ChangeBalanceGateway.Grpc.SpotChangeBalanceService/PciDssDeposit',
            ChangeBalance__pb2.PciDssDepositGrpcRequest.SerializeToString,
            ChangeBalance__pb2.ChangeBalanceGrpcResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Swap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service.ChangeBalanceGateway.Grpc.SpotChangeBalanceService/Swap',
            ChangeBalance__pb2.SwapGrpcRequest.SerializeToString,
            ChangeBalance__pb2.ChangeBalanceGrpcResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TransferFeeShareToServiceWallet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service.ChangeBalanceGateway.Grpc.SpotChangeBalanceService/TransferFeeShareToServiceWallet',
            ChangeBalance__pb2.FeeTransferRequest.SerializeToString,
            ChangeBalance__pb2.ChangeBalanceGrpcResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
