# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from GRPC.Kyc import IKycStatusService_pb2 as IKycStatusService__pb2


class KycStatusServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BlockDeposits = channel.unary_unary(
                '/Service.KYC.Grpc.KycStatusService/BlockDeposits',
                request_serializer=IKycStatusService__pb2.ChangeOperationStatusRequest.SerializeToString,
                response_deserializer=IKycStatusService__pb2.OperationResponse.FromString,
                )
        self.BlockTrades = channel.unary_unary(
                '/Service.KYC.Grpc.KycStatusService/BlockTrades',
                request_serializer=IKycStatusService__pb2.ChangeOperationStatusRequest.SerializeToString,
                response_deserializer=IKycStatusService__pb2.OperationResponse.FromString,
                )
        self.BlockWithdrawals = channel.unary_unary(
                '/Service.KYC.Grpc.KycStatusService/BlockWithdrawals',
                request_serializer=IKycStatusService__pb2.ChangeOperationStatusRequest.SerializeToString,
                response_deserializer=IKycStatusService__pb2.OperationResponse.FromString,
                )
        self.GetKycStatus = channel.unary_unary(
                '/Service.KYC.Grpc.KycStatusService/GetKycStatus',
                request_serializer=IKycStatusService__pb2.KycStatusRequest.SerializeToString,
                response_deserializer=IKycStatusService__pb2.KycStatusResponse.FromString,
                )
        self.SetKycLevel = channel.unary_unary(
                '/Service.KYC.Grpc.KycStatusService/SetKycLevel',
                request_serializer=IKycStatusService__pb2.SetKycLevelRequest.SerializeToString,
                response_deserializer=IKycStatusService__pb2.OperationResponse.FromString,
                )
        self.SetKycStatuses = channel.unary_unary(
                '/Service.KYC.Grpc.KycStatusService/SetKycStatuses',
                request_serializer=IKycStatusService__pb2.SetOperationStatusRequest.SerializeToString,
                response_deserializer=IKycStatusService__pb2.OperationResponse.FromString,
                )
        self.UnblockDeposits = channel.unary_unary(
                '/Service.KYC.Grpc.KycStatusService/UnblockDeposits',
                request_serializer=IKycStatusService__pb2.ChangeOperationStatusRequest.SerializeToString,
                response_deserializer=IKycStatusService__pb2.OperationResponse.FromString,
                )
        self.UnblockTrades = channel.unary_unary(
                '/Service.KYC.Grpc.KycStatusService/UnblockTrades',
                request_serializer=IKycStatusService__pb2.ChangeOperationStatusRequest.SerializeToString,
                response_deserializer=IKycStatusService__pb2.OperationResponse.FromString,
                )
        self.UnblockWithdrawals = channel.unary_unary(
                '/Service.KYC.Grpc.KycStatusService/UnblockWithdrawals',
                request_serializer=IKycStatusService__pb2.ChangeOperationStatusRequest.SerializeToString,
                response_deserializer=IKycStatusService__pb2.OperationResponse.FromString,
                )


class KycStatusServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BlockDeposits(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BlockTrades(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BlockWithdrawals(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetKycStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetKycLevel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetKycStatuses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnblockDeposits(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnblockTrades(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnblockWithdrawals(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KycStatusServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BlockDeposits': grpc.unary_unary_rpc_method_handler(
                    servicer.BlockDeposits,
                    request_deserializer=IKycStatusService__pb2.ChangeOperationStatusRequest.FromString,
                    response_serializer=IKycStatusService__pb2.OperationResponse.SerializeToString,
            ),
            'BlockTrades': grpc.unary_unary_rpc_method_handler(
                    servicer.BlockTrades,
                    request_deserializer=IKycStatusService__pb2.ChangeOperationStatusRequest.FromString,
                    response_serializer=IKycStatusService__pb2.OperationResponse.SerializeToString,
            ),
            'BlockWithdrawals': grpc.unary_unary_rpc_method_handler(
                    servicer.BlockWithdrawals,
                    request_deserializer=IKycStatusService__pb2.ChangeOperationStatusRequest.FromString,
                    response_serializer=IKycStatusService__pb2.OperationResponse.SerializeToString,
            ),
            'GetKycStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKycStatus,
                    request_deserializer=IKycStatusService__pb2.KycStatusRequest.FromString,
                    response_serializer=IKycStatusService__pb2.KycStatusResponse.SerializeToString,
            ),
            'SetKycLevel': grpc.unary_unary_rpc_method_handler(
                    servicer.SetKycLevel,
                    request_deserializer=IKycStatusService__pb2.SetKycLevelRequest.FromString,
                    response_serializer=IKycStatusService__pb2.OperationResponse.SerializeToString,
            ),
            'SetKycStatuses': grpc.unary_unary_rpc_method_handler(
                    servicer.SetKycStatuses,
                    request_deserializer=IKycStatusService__pb2.SetOperationStatusRequest.FromString,
                    response_serializer=IKycStatusService__pb2.OperationResponse.SerializeToString,
            ),
            'UnblockDeposits': grpc.unary_unary_rpc_method_handler(
                    servicer.UnblockDeposits,
                    request_deserializer=IKycStatusService__pb2.ChangeOperationStatusRequest.FromString,
                    response_serializer=IKycStatusService__pb2.OperationResponse.SerializeToString,
            ),
            'UnblockTrades': grpc.unary_unary_rpc_method_handler(
                    servicer.UnblockTrades,
                    request_deserializer=IKycStatusService__pb2.ChangeOperationStatusRequest.FromString,
                    response_serializer=IKycStatusService__pb2.OperationResponse.SerializeToString,
            ),
            'UnblockWithdrawals': grpc.unary_unary_rpc_method_handler(
                    servicer.UnblockWithdrawals,
                    request_deserializer=IKycStatusService__pb2.ChangeOperationStatusRequest.FromString,
                    response_serializer=IKycStatusService__pb2.OperationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Service.KYC.Grpc.KycStatusService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KycStatusService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BlockDeposits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service.KYC.Grpc.KycStatusService/BlockDeposits',
            IKycStatusService__pb2.ChangeOperationStatusRequest.SerializeToString,
            IKycStatusService__pb2.OperationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BlockTrades(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service.KYC.Grpc.KycStatusService/BlockTrades',
            IKycStatusService__pb2.ChangeOperationStatusRequest.SerializeToString,
            IKycStatusService__pb2.OperationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BlockWithdrawals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service.KYC.Grpc.KycStatusService/BlockWithdrawals',
            IKycStatusService__pb2.ChangeOperationStatusRequest.SerializeToString,
            IKycStatusService__pb2.OperationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetKycStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service.KYC.Grpc.KycStatusService/GetKycStatus',
            IKycStatusService__pb2.KycStatusRequest.SerializeToString,
            IKycStatusService__pb2.KycStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetKycLevel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service.KYC.Grpc.KycStatusService/SetKycLevel',
            IKycStatusService__pb2.SetKycLevelRequest.SerializeToString,
            IKycStatusService__pb2.OperationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetKycStatuses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service.KYC.Grpc.KycStatusService/SetKycStatuses',
            IKycStatusService__pb2.SetOperationStatusRequest.SerializeToString,
            IKycStatusService__pb2.OperationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UnblockDeposits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service.KYC.Grpc.KycStatusService/UnblockDeposits',
            IKycStatusService__pb2.ChangeOperationStatusRequest.SerializeToString,
            IKycStatusService__pb2.OperationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UnblockTrades(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service.KYC.Grpc.KycStatusService/UnblockTrades',
            IKycStatusService__pb2.ChangeOperationStatusRequest.SerializeToString,
            IKycStatusService__pb2.OperationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UnblockWithdrawals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service.KYC.Grpc.KycStatusService/UnblockWithdrawals',
            IKycStatusService__pb2.ChangeOperationStatusRequest.SerializeToString,
            IKycStatusService__pb2.OperationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
